# Generated by Django 4.2.7 on 2023-12-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinturon',
            old_name='cod_producto_cint',
            new_name='cod_producto_cinto',
        ),
    ]
